# Generated by Django 5.2 on 2025-04-05 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_rename_message_chat_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
